application: epilogue-demo
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /_ah/login_required
  script: do_openid_login.py

- url: /scripts
  static_dir: scripts

- url: /forms
  static_dir: forms

- url: /.*
  script: epilogue.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest